### ISSUE TITLE
sendVote.php duplicate votes does not update $votedList correctly

### ISSUE THREAD

**Issue by Dahlgren** [ArmaSE/Poll#3]
The vote loop inserts voted entries into null variable `$voted`
https://github.com/ArmaSE/Poll/blob/1596945cf932f32c077866ec015c667d5d3ede3b/sendVote.php#L21

should be `$votedList`
https://github.com/ArmaSE/Poll/blob/1596945cf932f32c077866ec015c667d5d3ede3b/sendVote.php#L16-L18

**Comment by obliv1on** [comment]
Variable reference has been fixed to point towards the correct variable.
